services:
  - type: web
    name: modiva-fashion
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn modeva.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: modeva.settings
