services:
  - type: web
    name: modeva
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn modeva.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: modeva.settings
      - key: PYTHON_VERSION
        value: 3.12.4
